import smtplib, ssl
from configs.etl_base import EtlBase # import all config
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

class Emailer:

    def __init__(self,client,config_name):
        EtlBase.__init__(self)
        self.host = self.appConfig[client][config_name]['host'] 
        self.port = self.appConfig[client][config_name]['port'] 
        self.username = self.appConfig[client][config_name]['username']  
        self.password = self.appConfig[client][config_name]['password'] 
        self.sender_email = self.appConfig[client][config_name]['sender_email']  
        self.receivers_emails = self.appConfig[client][config_name]['receivers_emails'] 

    def _bindReport_body(self,title,reportDate,message):
        exportReport = """\
        <html xmlns='http://www.w3.org/1999/xhtml'>
        <head>
            <meta http-equiv='Content-Type' content='text/html; charset=utf-8' />
            <title>Untitled Document</title>
        </head>
        <body style="background-color: #f5f5f5; width:100%; margin:auto;text-align: center;">
            <table style="width:600px; margin:auto; background-color: #fff; padding-top:50px; padding-left:50px; padding-right:50px; padding-bottom:50px;">
                <tr style="width:600px;">
                    <td style="border-bottom: 1px solid #dddddd; padding-bottom:10px;"><span style="display: block;"><a href="https://www.insightincloud.com"><img src="https://www.insightincloud.com/Content/Theme/images/branding.png"></a></span></td>
                </tr>
                <tr style="width:600px; padding-top:0; marging:0px;">
                    <td style="padding-top: 20px;"><h2 style="margin: 0px;font-family: arial; font-size: 18px; line-height: 20px;">{}</h2>
                    <span style="display:block;font-family: arial; font-size: 14px; color:#757575; line-height: 20px;">Report date: {}</span></td>
                </tr>
                <tr style="width:600px; padding-top:0; marging:0px;">
                    <td>
                        {}
                    </td>
                </tr>
            </table>
            <table style="width:600px; margin:auto; background-color: #f5f5f5; padding-left:50px; padding-right:50px; padding-bottom:50px;">
                <tr>
                    <td style="margin: 0px; font-family: arial; font-size: 14px;margin-bottom:20px; display:block; color:#757575; text-align:center; padding-top:20px;">
                    This message is automatically generated by InsightIn Health. Please do not reply to this message.</td>
                </tr>
            </table>
        </body>
        </html>
        """.format(title,reportDate,message)
        return exportReport

    def _send_mail(self,message):
        try:
            server = smtplib.SMTP(self.host, self.port)
            server.ehlo()
            server.starttls()
            server.login(self.username, self.password)
            server.sendmail(self.sender_email, self.receivers_emails, message.as_string())
            server.close()
            print('successfully sent the mail')
        except:
            print("failed to send mail")
    
    def _format_message(self,subject,message_body):
        convertedHtml = MIMEText(message_body, "html")
        formetted_body = MIMEMultipart("alternative")
        formetted_body["Subject"] = subject
        formetted_body.attach(convertedHtml)
        formetted_body["From"] = self.sender_email
        formetted_body["To"] = ", ".join(self.receivers_emails) 
        return  formetted_body    
        
            